"""Systems JJ-SYS-07 to JJ-SYS-11.

07 is verbatim from johnjayasankar.com, except that product and venue names are
replaced with generic descriptions.

08-10 are John's independent products, the three featured on his Labs site
(labs.johnjayasankar.com). Their cases keep the live site's wording and extend it
with facts stated on each product's own public site, captured September 2026:
ride-lens2.vercel.app, rail-drop3.vercel.app and daylight-app-wine.vercel.app.
Nothing is inferred from code or invented. Figures shown in the stories are the
products' own sample data (RailDrop's sample board, Daylight's Balanced preset)
or clearly labelled illustrations.

11 is Gridiron, John's live football command center, described from its own
README and changelog at version 0.5.1 (github.com/johnjayasankar-afk/gridiron,
live at gridiron-pink-chi.vercel.app). Every figure in its story is one the app
shows while replaying its captured NFL Week 1 games; nothing is a sample or a
mock-up. How it was built is stated as it happened: John's brief, implemented
with Claude Code.

The `lab` block carries the Labs site's card copy: number, category, tagline,
description, and what each product refuses to fake."""

from data_systems_a import B

SYSTEMS_B = [
  dict(
    id='JJ-SYS-07', slug='margin-simulator', name='Pre-Trade Margin Simulator', short='Margin Simulator', facet='markets',
    kind='0→1 · Pre-trade', read='3 min',
    title='Pre-trade simulator that made capital a decision, not a surprise',
    lede='A simulation engine that showed the next trade’s capital cost across venues before the desk committed. Comparing incremental with standalone cost made portfolio offsets visible.',
    org='OpenGamma · Trading Technologies', stage='0→1 launch', year='2022 to 2023', role='Product Analyst',
    metrics=[('0→1', 'originated and shipped'), ('up to −30%', 'initial margin'), ('20+', 'enterprise clients')],
    ledger=('0→1 · Pre-trade', '0→1', 'originated and shipped'),
    bay=dict(title='Margin simulator · pre-trade simulation', sub='Portfolio margin known · the next trade’s capital impact is not',
             big='up to −30%', big_sub='initial margin · potential, not guaranteed',
             foot='Schematic pre-trade surface · simulate to decide venue, broker or product'),
    phases=[('Base',     .05, 'Current margin on the book. The next trade’s cost is still unknown.'),
            ('+ Trade',  .20, 'Hypothetical trade sits outside the book until you simulate venues.'),
            ('Simulate', .34, 'Same trade across two exchanges and OTC, before you execute.'),
            ('Compare',  .70, 'Incremental vs standalone: offsets in the book can cut cost by up to 30% when they apply. Observed potential, not a guarantee.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Front-office teams lacked a simple way to compare the incremental margin impact of a proposed trade across brokers, venues, and products before execution. Capital showed up after the fact.'),
      B('decision', 'Decision', 'Product decision', 'Build a simulation engine in the trading workflow: current portfolio plus a hypothetical trade, simulated against the native clearing methodologies of two major exchanges across OTC and exchange-traded venues.'),
      B('flow', 'Flow', 'Flow', [('Current', 'Portfolio IM is known', 'Teams can see where they stand. They cannot see the next trade.'),
                                 ('Scenario', 'Propose, then simulate', 'Add the hypothetical position and recompute margin before execution.'),
                                 ('Decide', 'Compare allocations', 'Cheaper venue, broker, or product becomes a pre-trade choice.')], kind='flow'),
      B('plain', 'In plain terms', 'In plain terms', ['Before you add a trade, you need its capital cost, not after the fill',
                                                      'The same trade can cost different amounts at each exchange or OTC',
                                                      'Incremental cost (on top of your book) can be lower than standalone when offsets exist',
                                                      '“Up to −30%” is observed potential when offsets apply, not guaranteed savings on every trade'], kind='list'),
      B('owned', 'What I owned', 'What I owned', ['Originated and shipped the 0→1 simulator from discovery through launch',
                                                  'Led discovery across trading, treasury, risk, and operations so the engine answered a real pre-trade question',
                                                  'Made incremental vs standalone cost a first-class product concept, not a spreadsheet side path'], kind='list'),
      B('how', 'How it works', 'How it works', ['Starts from the current portfolio, not a blank page',
                                                'Adds, edits, or removes a proposed position as a hypothetical',
                                                'Simulates initial margin across broker, venue, and product before execution',
                                                'Uses native clearing methodologies as validation anchors so the comparison is decision-grade'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product Analyst. Originated and shipped the 0→1 product. Led discovery across trading, treasury, risk, and operations.',
        kind='role', tags='Scenario before trade · Native methodology · Decision UX · Capital efficiency'),
      B('impact', 'Impact', 'Impact', 'Institutional clients identified allocations with up to 30% lower initial margin for equivalent risk. Discovery and adoption spanned 20+ enterprise clients: banks, asset managers, commodity firms, and hedge funds.'),
    ],
    also=['platform', 'ridelens', 'raildrop'],
  ),
  dict(
    id='JJ-SYS-08', slug='ridelens', name='RideLens', short='RideLens', facet='independent',
    kind='Labs · Consumer', read='5 min',
    title='RideLens: every ride, one comparison',
    lede='Live roads. Real rate cards. Uber, Lyft, Empower, and Curb ranked before you open four apps and guess.',
    org='Independent · Labs', stage='0→1 · live product', year='2026', role='Product, design, and build',
    metrics=[('4', 'providers, one board'), ('3', 'ways to rank a trip'), ('Honest', 'ranges stay ranges')],
    ledger=('Labs · Consumer', '4', 'providers, one board'),
    lab=dict(n='01', cat='Consumer', tagline='Every ride, one comparison.',
             blurb='Live roads. Real rate cards. Uber, Lyft, Empower, and Curb ranked before you open four apps and guess.',
             does=['Map the trip once on live roads, then line up four providers side by side',
                   'Rank the same quotes by Price, Soonest, or Value',
                   'Estimates move with traffic, time of day, hotspots, and weather'],
             rule='Ranges stay ranges.',
             rule_body='When a fare is a range, both ends stay on the board. RideLens never invents a midpoint to look decisive.'),
    live='https://ride-lens2.vercel.app/', embed=True,
    bay=dict(title='RideLens · compare board', sub='Illustrative trip · four providers, three sort rules',
             big='4 → 1', big_sub='providers → one board',
             foot='Illustrative quote types, not live fares · the final fare is always confirmed in the provider app'),
    phases=[('Route',   .12, 'Illustrative: map the trip once on live roads; conditions feed the marketplace model.'),
            ('Price',   .38, 'Illustrative: the same four quotes, ranked by lowest listed fare.'),
            ('Soonest', .62, 'Illustrative: the same quotes, ranked by soonest pickup.'),
            ('Value',   .86, 'Illustrative: fare and wait traded off. Ranges stay ranges.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Getting across town meant bouncing between apps, comparing stale screenshots in my head, and hoping the fare I saw was still the fare I would pay. Ranges got flattened into fake precision. Wait times lived in a different mental tab than price.'),
      B('decision', 'Decision', 'Product decision', 'Build one decision surface. Map the route once. Pull published rate cards and a marketplace that moves with time of day, weather, and hotspots. Keep estimates as estimates, ranges as ranges, and upfront quotes as upfront. Rank by Price, Soonest, or Value, then hand off to the provider to book.'),
      B('flow', 'Flow', 'Flow', [('Fragmented', 'Four apps, one guess', 'Price in one place. ETA in another. Memory in between.'),
                                 ('One surface', 'Route once, compare once', 'Same trip. Side-by-side cards. Rank modes you can trust.'),
                                 ('Decide', 'Pick, then book there', 'RideLens ranks. The provider still owns the ride.')], kind='flow'),
      B('does', 'What it does', 'What it does', ['Search From and To, or Quick fill a hub: JFK, LGA, EWR, Times Sq, Grand Central, or Brooklyn Bridge',
                                                 'Use your current location or swap the ends, then map the route once on live roads',
                                                 'Line up Uber, Lyft, Empower, and Curb side by side on one board',
                                                 'Rank the same quotes by Price, Soonest, or Value; ⌘Enter runs the compare',
                                                 'Open the provider to book. The final fare is always confirmed in the provider app'], kind='list'),
      B('contract', 'Contract', 'The comparison contract', [('Estimates stay estimates', 'A modeled fare is shown as an estimate, never dressed up as a quote.'),
                                                             ('Ranges stay ranges', 'When a fare is a range, both ends stay on the board. No invented midpoint.'),
                                                             ('Upfront stays upfront', 'An upfront price is kept distinct from anything modeled.'),
                                                             ('Expired quotes never win', 'A stale quote cannot take the top of the board.')],
        kind='grid', note='I wanted a product that respects uncertainty. The board keeps these rules whichever way it is sorted.'),
      B('model', 'Under the hood', 'Under the hood', ['Photon for place search and OSRM for routing on live roads',
                                                      'Fare math built on published rate cards',
                                                      'A marketplace model that tracks time, zone heat, and weather, so estimates update with traffic, time of day, and hotspots',
                                                      'Side-by-side provider cards that auto-refresh after the first compare'], kind='list'),
      B('why', 'Why I built it', 'Why I built it', ['I live in a city where the right ride changes with the clock, and where opening four apps is its own chore',
                                                    'I wanted a product that respects uncertainty: never invent a midpoint just to look decisive',
                                                    'The interesting work was the comparison contract, not another map widget'], kind='list'),
      B('built', 'How it was built', 'How it was built', ['I directed product design, ranking rules, and quote honesty end-to-end',
                                                          'Implemented and iterated the live app in Cursor; ownership of decisions and quality stays with me',
                                                          'Marketplace behavior is modeled from published rate cards and conditions; booking still happens on the provider',
                                                          'Shipped as a working product, not a pitch deck. Adoption claims are not the point of this case'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product, design, and build. Designed the comparison model, quote honesty rules, ranking modes, and the live marketplace surface.',
        kind='role', tags='Multi-provider · Live routing · Quote honesty · Price · Soonest · Value'),
      B('impact', 'Impact', 'Impact', 'A working product: Photon search, OSRM routing, side-by-side provider cards, and auto-refresh after the first compare. Built end-to-end in Cursor and shipped live. I made it because I kept paying the tax of not knowing which ride was actually better tonight.'),
      B('live', 'Live', 'Try the live product', 'Explore the working product below without leaving this case. The frame is the live app, not a mock; open it full-size for the full journey.', kind='live'),
    ],
    also=['raildrop', 'daylight', 'setup-agent'],
  ),
  dict(
    id='JJ-SYS-09', slug='daylight', name='Daylight', short='Daylight', facet='independent',
    kind='Labs · Native macOS', read='6 min',
    title='Daylight: your screen, through the day',
    lede='Adaptive display lighting for macOS. Warmth and brightness on a schedule you set: gradual, offline, and honest about what it is doing and why.',
    org='Independent · Labs', stage='Shipped · v1.0.0', year='2026', role='Product, design, and build',
    metrics=[('6', 'layers, one fixed order'), ('3', 'levels of certainty'), ('263', 'tests, no dependencies')],
    ledger=('Labs · Native macOS', '6', 'layers, one fixed order'),
    lab=dict(n='02', cat='Native', tagline='Your screen, through the day.',
             blurb='Warmth and brightness on a schedule you set: gradual, offline, and honest about what it is doing and why.',
             does=['Shift warmth and brightness gradually on a schedule, or follow the sun',
                   'Decide every control on one printed, six-layer ladder',
                   'Read back after every write, and say so when another app took over'],
             rule='Success is not evidence.',
             rule_body='Daylight separates what it asked for, what macOS accepted, and what it could read back and confirm.'),
    live='https://daylight-app-wine.vercel.app/', embed=False,
    bay=dict(title='Daylight · display schedule', sub='Balanced preset · warmth and brightness decided separately',
             big='6 layers', big_sub='one fixed order',
             foot='Schematic · step values from the Balanced preset · the sentence is one the app writes'),
    phases=[('Schedule', .12, 'Balanced preset: 6500 K by day, 4200 K at 19:00, 3200 K at 21:30, 2800 K at 23:30.'),
            ('Resolve',  .38, 'Six layers in a fixed order: the highest layer that speaks about a control wins it.'),
            ('Explain',  .62, 'An app rule holds warmth neutral while dimming still comes from the schedule, and a sentence says so.'),
            ('Confirm',  .86, 'Asked, accepted, confirmed: an API returning success is not evidence the display changed.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Most display utilities either fight Night Shift and f.lux silently, claim medical outcomes they cannot prove, or hide what actually changed your screen. I wanted something honest: a schedule that survives time zones and DST, rules that do not discard half the state, and language that admits when macOS did not take the write.'),
      B('decision', 'Decision', 'Product decision', 'Ship a menu-bar app that runs the same schedule engine its website demonstrates. Put every source of control on one printed ladder of six layers, and decide warmth and brightness separately so a rule that only dims cannot discard the schedule’s warmth. Distinguish asked, accepted, and confirmed. Notice competing color-table writers instead of fighting them. Never ask for location, network, or analytics.'),
      B('flow', 'Flow', 'Flow', [('Schedule', 'Through the day', 'Anchors on the clock. Fades in mired. Survives DST and midnight.'),
                                 ('Explain', 'Name the cause', 'Every state has a sentence. Precedence is printed, not implied.'),
                                 ('Confirm', 'Trust the readback', 'Success from an API is not evidence. Competition is reported.')], kind='flow'),
      B('does', 'What it does', 'What it does', ['Shifts warmth and brightness gradually on a schedule you set, from presets Balanced, Subtle, Extra Warm, and Follow the sun',
                                                 'Follow the sun uses real sunrise and sunset, computed on your Mac from a place you choose: 101 cities built in, or coordinates',
                                                 'Lives in the menu bar: warmth and brightness, every mode, a pause with a duration, and restore, all one click from the icon',
                                                 'A pause lasts fifteen minutes, an hour, until the next scheduled change, or until you say otherwise, and tells you when it ends',
                                                 'The icon fills in proportion to how warm the setting is, and shows paused and off as distinct shapes rather than colors',
                                                 'Schedules travel: Daylight imports the file its website writes, and a link carries a whole schedule to anyone else'], kind='list'),
      B('ladder', 'The ladder', 'Six layers, one fixed order', [('Restored', 'Restore normal output. Top of the ladder, overrules everything below.'),
                                                                ('Paused', 'Paused until you resume.'),
                                                                ('Manual override', 'You reached for the slider.'),
                                                                ('App rule', 'An app that needs true color.'),
                                                                ('Workspace', 'Where you are working.'),
                                                                ('Schedule', 'A schedule, warm by evening. The base layer, if nothing above it speaks.')],
        kind='grid', note='The highest layer that speaks about a control wins it, and warmth and brightness are decided separately, so a rule that only dims cannot quietly discard your schedule’s warmth. There are no user-assignable priorities: a rules system you can predict beats one you can fully rewire.'),
      B('explain', 'Explainable', 'It tells you what it is doing', [('Every state has a sentence', 'Plain language naming whatever is responsible, written by the same resolver the app runs and checked against it across every combination of the six layers.'),
                                                                    ('Three levels of certainty', 'What it asked for, what macOS accepted, and what it could read back and confirm. Each display reports which applies. An API returning success is not evidence that anything changed.'),
                                                                    ('It notices the competition', 'f.lux and Night Shift write to the same color table. Daylight reads back after every write and says so when something else has overwritten it. It will not fight another app, or disable one behind your back.')],
        kind='grid', note='“Your display is neutral because Colour Work is active for this app. Dimming comes from Balanced.” The app writes sentences like that one for every state.'),
      B('details', 'Details', 'The details that took the longest', [('Schedules that survive real life', 'Daylight-saving changes, time-zone moves, clocks corrected by hand, schedules that cross midnight, night shifts, non-Western weeks, polar day and night. Anchors follow the clock and fades follow elapsed time; a test pins the 23-hour day that once put a schedule an hour out.'),
                                                                     ('Fades paced by perception', 'Interpolation runs in mired rather than kelvin, because 2000 to 3000 K is a large visible change and 8000 to 9000 K is nearly invisible. A 90-minute ramp writes about once a minute instead of once a frame.'),
                                                                     ('Displays remembered properly', 'Settings key to a durable display identity, never an index that is reassigned on every dock and wake. Identical monitors that cannot be told apart are reported as ambiguous instead of guessed at.'),
                                                                     ('It refuses a suspicious baseline', 'Before adjusting anything it validates what normal means for a display. With f.lux running, the table once read back R 1.00 / G 0.36 / B 0.10; a test is pinned to those exact numbers.'),
                                                                     ('Getting out of the way', '⇧⌥⌘R restores normal output from anywhere with no permissions. Quitting restores your displays, and after a crash macOS restores the color table itself, verified under SIGKILL, which is why there is no watchdog helper.'),
                                                                     ('Sunrise without a permission prompt', 'Solar times are computed on your Mac from a place you choose. It can suggest a starting point from your time zone, never asks macOS where you are, and makes no network requests.')],
        kind='grid'),
      B('claims', 'Not claimed', 'What it does not claim', ['A comfort and routine tool, not a medical one: it does not prevent eye damage, treat eye strain, or improve your sleep',
                                                            'No invented circadian, eye-health, or melatonin scores. There is no score of any kind',
                                                            'Temperature values are approximate display targets, not measurements of emitted light',
                                                            'Brightness is software dimming, not backlight control, and the app says so wherever the word appears',
                                                            'It does not calibrate your display or make its color accurate, including in Colour Work mode'], kind='list'),
      B('privacy', 'Privacy', 'It stays on your Mac', [('Account', 'None'), ('Network requests', 'None, ever'), ('Location permission', 'Never asked'),
                                                       ('Analytics or telemetry', 'None'), ('Screen contents, keystrokes, camera', 'Never touched'),
                                                       ('Settings', 'One readable file to export, import, or delete'), ('History', 'Off by default; switching it off deletes what was kept')],
        kind='specs', note='If you turn on app rules, Daylight reads the identifier of the frontmost application while deciding what to do, and keeps no record of it.'),
      B('unfinished', 'Unfinished', 'Two things that are not finished', [('Multi-display on real hardware', 'Every path is written and covered against simulated devices, but only one display was attached during development. Daylight --diagnose shows what your own displays report.'),
                                                                         ('Backlight over DDC', 'External-monitor backlight control has unit-tested packet framing, but the hardware path has never exchanged a byte with a monitor, so it is off by default.')],
        kind='grid', note='Both are stated on the product’s own site, next to the download.'),
      B('why', 'Why I built it', 'Why I built it', ['I wanted display comfort without medical theater, scores, or melatonin claims',
                                                    'Existing tools either hide failures or overwrite each other quietly. I wanted the opposite',
                                                    'The interesting work was the control model: one printed ladder, durable display identity, and honest certainty'], kind='list'),
      B('built', 'How it was built', 'How it was built', ['Directed product, design, and implementation in Cursor; ownership and quality judgment are mine',
                                                          'Native macOS with no third-party dependencies; it builds with Command Line Tools alone, no Xcode required',
                                                          '263 tests ship with the source, and the website runs the app’s own schedule engine and color math rather than a picture of it',
                                                          'Solar position follows the published NOAA algorithm and the color-temperature approximation follows Kim et al. (2002), both implemented from their descriptions',
                                                          'Signed v1.0.0, 2.1 MB, for Apple Silicon and Intel on macOS 14 or later. Not notarized yet, so Gatekeeper needs one extra step on first open'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product, design, and build. Designed the schedule model, the six-layer precedence ladder, certainty reporting, and the menu-bar product that stays out of the way.',
        kind='role', tags='Schedule fades · Explainable state · Readback certainty · No location permission'),
      B('impact', 'Impact', 'Impact', 'A signed macOS app (v1.0.0) with four schedule presets, app rules, pause and restore, durable display identity, and a website that runs the same schedule engine. Built end-to-end with no third-party dependencies. Not notarized yet, so Gatekeeper needs one extra step on first open, and the site says so.'),
      B('live', 'Live', 'See the product', 'Daylight is a signed macOS menu-bar app. Its site runs the real schedule engine in the browser, explains Gatekeeper and certainty, and carries the download and the source.', kind='live'),
    ],
    also=['ridelens', 'raildrop', 'platform'],
  ),
  dict(
    id='JJ-SYS-10', slug='raildrop', name='RailDrop', short='RailDrop', facet='independent',
    kind='Labs · Consumer', read='5 min',
    title='RailDrop: know when your train gets cheaper',
    lede='Book the trip. Watch every bookable Amtrak option across your window. One email when a listed fare actually drops. Never an invented price.',
    org='Independent · Labs', stage='0→1 · live product', year='2026', role='Product, design, and build',
    metrics=[('±1 day', 'default watch window'), ('1 email', 'only when it improves'), ('0', 'invented prices')],
    ledger=('Labs · Consumer', '±1 day', 'default watch window'),
    lab=dict(n='03', cat='Consumer', tagline='Know when your train gets cheaper.',
             blurb='Book the trip. Watch every bookable Amtrak option across your window. One email when a listed fare actually drops.',
             does=['Watch every bookable rail option across the day before, the day, and the day after',
                   'Scan immediately, then again morning, afternoon, and evening',
                   'One email when a listed fare beats what you paid'],
             rule='Never an invented price.',
             rule_body='If the live board is down, RailDrop says so. It never guesses a fare, a change fee, or an itinerary.'),
    live='https://rail-drop3.vercel.app/', embed=True,
    bay=dict(title='RailDrop · Amtrak fare watch', sub='Sample board · BOS → NYP · you paid $128',
             big='$128 → $47', big_sub='paid → cheapest listed',
             foot='Sample board from RailDrop’s own site · listed fares · confirm on Amtrak'),
    phases=[('Booked',   .10, 'Illustrative: stations, date, and what you actually paid become the baseline.'),
            ('Watching', .36, 'Illustrative: the first scan runs immediately, then morning, afternoon, and evening.'),
            ('Board',    .60, 'Illustrative: every bookable option across ±1 day, measured against what you paid.'),
            ('Alert',    .86, 'Illustrative: one email when a listed fare beats what you paid. Confirm on Amtrak.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Northeast Corridor trips are booked early for peace of mind, then the board keeps moving. Flexible tickets can be changed, but only if you notice the drop. Most people do not. They paid $128 and never learn Regional 95 is sitting at $47.'),
      B('decision', 'Decision', 'Product decision', 'Watch the corridor, not just the train you bought. Default window is travel day ±1. Compare against what you actually paid. Surface every eligible rail option. Alert once when the opportunity improves. Keep booking on Amtrak: copy the itinerary, confirm there, never invent a deep link or a fare.'),
      B('flow', 'Flow', 'Flow', [('Booked', 'You already paid', 'Peace of mind first. The board does not freeze for you.'),
                                 ('Watch', 'Same stations, every train', 'Regional, Acela, connections, not just your seat.'),
                                 ('Alert', 'One precise email', 'Opportunity improved. Confirm on Amtrak before you change anything.')], kind='flow'),
      B('how', 'How it works', 'How it works', [('Book on Amtrak', 'Whatever you actually paid is the number every train is measured against.'),
                                                ('Tell RailDrop the trip', 'Stations, date, and price. The window is searched immediately.'),
                                                ('One email when it drops', 'Confirm on Amtrak before you change anything.')],
        kind='grid', note='No account required. Watch a trip as a guest, and add an email only if you want fare-drop alerts.'),
      B('watch', 'The watch', 'The watch discipline', ['Same stations, every train: Regional, Acela, and connections, not just the train you already bought',
                                                      '±1 day by default: the day before, your travel day, and the day after. If tomorrow is cheaper than today, you should know',
                                                      'Checks immediately when a watch is created, then morning, afternoon, and evening; C rechecks on demand',
                                                      'Already booked a specific train? Add the train number and the board pins it next to the cheapest listed option',
                                                      'One precise alert: email only when the opportunity actually improves'], kind='list'),
      B('board', 'The board', 'Reading the board', [('Beats your train', 'Cheaper and not slower than yours, or faster and not more expensive.'),
                                                    ('Filters that fit a trip', 'Leave after, arrive by, a duration cap, and a 30-minute arrive buffer.'),
                                                    ('Change fees, only if you say so', 'Type an estimate or tap $10, $20, or $50. Change rules depend on Flexible, Value, or Saver, so no fee is ever invented.'),
                                                    ('What moved, and how close', 'The board shows what moved and how close departure is. The decision to change stays yours.'),
                                                    ('Built for the keyboard', 'J and K focus a train, H hides it, U undoes, Y copies you versus it, W copies the window, F copies Amtrak fields.'),
                                                    ('Shareable in one line', 'T copies stations, the cheapest listed train, and what you paid, for anyone else on the trip.')],
        kind='grid'),
      B('rules', 'Will not do', 'What it will not do', [('Invent Amtrak prices', 'If the live board is down, you see that, not a guess.'),
                                                        ('Fake an itinerary', 'No deep links into invented Amtrak itineraries. You copy trip details and book there.'),
                                                        ('Rebook for you', 'It watches and ranks. You book on Amtrak, then tell it what you actually paid.'),
                                                        ('Spam you', 'Alerts fire only when the opportunity actually improves.')], kind='grid'),
      B('why', 'Why I built it', 'Why I built it', ['I kept buying Flexible Amtrak tickets early, then learning too late that a later Regional was half the price',
                                                    'Existing tools either invent certainty or bury the signal in noise. I wanted quiet honesty',
                                                    'The product is the watch discipline: same stations, every rail option, alert only when it matters'], kind='list'),
      B('built', 'How it was built', 'How it was built', ['I directed the watch window, alert rule, and honesty constraints end-to-end',
                                                          'Implemented and iterated the live app in Cursor; product judgment and quality are mine',
                                                          'Alerts fire only when a listed fare beats what you paid; booking confirmation stays on Amtrak',
                                                          'A working launch, not a growth story. The case is about the discipline of the watch'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product, design, and build. Designed the watch window, honesty rules, alert discipline, and the live board that never pretends Amtrak is quieter than it is.',
        kind='role', tags='Fare watch · ±1 day board · No invented prices · You decide on Amtrak'),
      B('impact', 'Impact', 'Impact', 'A live product with immediate scans, scheduled rechecks, guest watches, optional email alerts, and a board that fails honestly when the source is down. Built end-to-end in Cursor. I made it after enough trips where the cheaper train was there the whole time. I just was not watching.'),
      B('live', 'Live', 'Try the live product', 'Explore the working product below without leaving this case. The frame is the live app, not a mock; open it full-size for the full journey.', kind='live'),
    ],
    also=['ridelens', 'daylight', 'fx-compression'],
  ),
  dict(
    id='JJ-SYS-11', slug='gridiron', name='Gridiron', short='Gridiron', facet='independent',
    kind='Labs · Live data', read='6 min',
    title='Gridiron: every game, every drive, one view',
    lede='A live NFL and college football command center. Every game gets its own 3D field with the reported ball spot, beside the score, win probability, and odds from named sources.',
    org='Independent · Labs', stage='0→1 · live product', year='2026', role='Product, design, and build',
    metrics=[('3', 'sources, each named'), ('0', 'guessed ball spots'), ('446', 'unit and integration tests')],
    ledger=('Labs · Live data', '3', 'sources, each named'),
    lab=dict(n='04', cat='Live data', tagline='Every game. Every drive. One view.',
             blurb='A live NFL and college football command center: a 3D field for every game, with the reported ball spot, win probability, and odds beside it.',
             does=['Follow every live NFL and college game, each on its own 3D field',
                   'Draw only reported spots: the ball, the line of scrimmage, the line to gain',
                   'Put ESPN win probability, DraftKings lines, and Kalshi prices beside the score'],
             rule='Reported, never guessed.',
             rule_body='Every spot, clock, and chance comes from a source that reported it. A missing ball spot says so; it is never guessed to midfield.'),
    live='https://gridiron-pink-chi.vercel.app/', embed=False,
    bay=dict(title='Gridiron · football command center', sub='NFL Week 1 replay · ARI at LAC · captured real games',
             big='6 → 1', big_sub='live games → one view',
             foot='Captured real games from Gridiron’s NFL Week 1 replay · figures as ESPN, DraftKings, and Kalshi reported them · not betting advice'),
    phases=[('Slate', .12, 'Replay of captured real games: six live at once, and Watch next names why ARI at LAC deserves attention.'),
            ('Drive', .38, 'Reported spots only: 10 plays and 65 yards to 2nd & Goal at the LAC 5, where the goal line is the line to gain.'),
            ('Odds', .62, 'Every chance is named: ESPN win probability LAC 70%, DraftKings closing lines, Kalshi LAC to win 73.5¢.'),
            ('Touchdown', .86, 'A 5-yard touchdown run, announced once, and ESPN’s model moves ARI +5 on the play.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'On a busy Saturday or NFL Sunday, following several games closely means switching between broadcasts, tabs, and scoreboards. A scoreboard says who leads. It does not say where the ball is, how the drive got there, or which game deserves attention next.'),
      B('decision', 'Decision', 'Product decision', 'Make the field the interface. Give every game its own 3D field with the reported ball spot, possession, line of scrimmage and line to gain, and let the slate, four games in focus and a single game page share one live state. Draw only what a source reported: when a spot, a line or a chance is missing, say so instead of filling it in.'),
      B('flow', 'Flow', 'Flow', [('Slate', 'Every game at once', 'Live games first, with Watch next naming why a game deserves attention.'),
                                 ('Field', 'Every drive, spatially', 'The ball moves between reported spots, never along an invented route.'),
                                 ('Moment', 'Know when it matters', 'Touchdowns, turnovers and red-zone trips, announced once and corrected honestly.')], kind='flow'),
      B('does', 'What it does', 'What it does', ['A slate of every live NFL and college game, live first, with notable situations and a Watch next strip that names its reasons',
                                                 'Focus on one, two or four games, or a wall of 4, 9 or 16, with a Director that follows the most important live situation and says why',
                                                 'A game page with a 3D field and three cameras, drive replay, game flow, play-by-play, leaders and team stats',
                                                 'ESPN win probability, DraftKings lines, and Kalshi prices beside every game that has them, each named by its source',
                                                 'Team pages, plus watch parties that follow the host’s view and push alerts for favorite teams on the full server build',
                                                 'A replay lab of captured real games for when nothing is live, labeled on every screen, on the full server build'], kind='list'),
      B('contract', 'Contract', 'Reported, never guessed', [('Spots come from the provider', 'The field-position label first, then the yard line, then the distance to the end zone. With none, the field says Ball spot unavailable.'),
                                                            ('Clocks are never counted down', 'A clock shows what the provider last reported, not a local timer.'),
                                                            ('Chances are never calculated', 'Win probability is ESPN’s model, lines are the sportsbook ESPN reports, prices are Kalshi’s, and each is named.'),
                                                            ('Replays say so', 'Captured games are labeled on every screen, and deliberately edited test scenarios say Synthetic.')],
        kind='grid', note='Routes, formations and tackle locations are not reported, so Gridiron never draws them. The ball sits on the center line because no live provider reports where it is across the field.'),
      B('field', 'The field', 'Reading the field', [('Away defends the left', 'The real stadium direction is not reported, so each field says which end each team defends.'),
                                                    ('Blue and amber', 'Blue marks the line of scrimmage and amber the line to gain. On goal to go, the goal line lights instead.'),
                                                    ('Shapes from the play type', 'Runs sweep and passes arc, kicks fly high, incompletions go out and come back, and sacks drop back.'),
                                                    ('Rulebook markings', 'Hash marks, numbers, the try line, goal posts and pylons follow the 2026 NFL and NCAA rulebooks.')], kind='grid'),
      B('odds', 'Odds', 'Odds and win probability', [('Win probability', 'ESPN’s model after each reported play, and its matchup predictor before kickoff.'),
                                                     ('Sportsbook lines', 'Spread, moneyline and total with their opening lines, and after a game, how the result compared with the closing lines.'),
                                                     ('Kalshi prices', 'Each team’s contract to win from Kalshi’s public market data, with no account or key, drawn beside ESPN’s model in game flow.')],
        kind='grid', note='Shown for information only, not as betting advice.'),
      B('engine', 'Engine', 'How it stays live', ['One server polls the provider for everyone and streams changes to each browser as small deltas, with a full resync when one cannot apply',
                                                  'A game you have open refreshes every 12 seconds and a game on screen every 25, inside one shared request budget',
                                                  'A spoiler delay holds scores, fields, odds and alerts on one timeline, so nothing leaks early',
                                                  'A provider failure shows as delayed or unavailable with its reason, and is never replaced with other data'], kind='list'),
      B('craft', 'Craft', 'Built to be watched', [('One canvas', 'A single WebGL canvas draws every field, and renders only when something changes.'),
                                                  ('2D when it has to', 'Reduced effects, a 2D mode of SVG fields with no WebGL at all, and reduced motion respected.'),
                                                  ('Accessible', 'Every field has a text summary, and an axe audit of WCAG 2.1 A and AA runs in the end-to-end suite.'),
                                                  ('Tested', '446 unit and integration tests and 60 Chrome journeys at version 0.5.1, run against captured real games.')], kind='grid'),
      B('limits', 'Not claimed', 'What it does not claim', ['Not official real-time tracking: the provider has its own delay, and a clock shows what was last reported',
                                                            'College play-by-play is often incomplete; those games say Score-only coverage and carry no win probability',
                                                            'Nothing was live while odds were built, so in-game line movement had not been observed; Gridiron calls them the latest lines reported',
                                                            'Odds and prices are information, not betting advice'], kind='list'),
      B('why', 'Why I built it', 'Why I built it', ['Following several games at once meant switching between broadcasts, tabs, and scoreboards',
                                                    'I wanted to understand the whole slate in seconds, see which games deserve attention, and follow drives spatially',
                                                    'It had to be useful while watching, at a desk, or keeping up without a broadcast at all'], kind='list'),
      B('built', 'How it was built', 'How it was built', ['I wrote the brief: the problem, the experience, the visual system, and the rule that nothing on screen is invented',
                                                          'Implemented and iterated with Claude Code, release by release from 0.1 to 0.5.1; product direction and quality judgment are mine',
                                                          'React 19, Vite and React Three Fiber on the client; a Node server with a shared polling engine and server-sent events',
                                                          'Deployed on Vercel as a bounded version that polls instead of streaming, and leaves out the replay lab, watch parties and push alerts, which need the persistent server'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product, design, and build. Wrote the brief, set the rule that nothing on screen is invented, and shipped the live product.',
        kind='role', tags='Live data · 3D fields · Reported spots only · Named sources'),
      B('impact', 'Impact', 'Impact', 'A live product: a 3D field for every game, Focus, the wall, and the Director, a game page with drive replay and game flow, ESPN win probability, DraftKings lines, and Kalshi prices, and team pages. The full server build adds the replay lab, watch parties, and push alerts, which the Vercel deployment leaves out. Shipped as a working product, not a pitch deck.'),
      B('live', 'Live', 'See the product', 'Gridiron runs live on Vercel. When no game is on, it says so, with the next kickoffs and recent finals, and every game page, past or live, opens from there.', kind='live'),
    ],
    also=['ridelens', 'raildrop', 'daylight'],
  ),
]
