"""Systems JJ-SYS-01 to JJ-SYS-06. Copy is taken verbatim from johnjayasankar.com
so the rebuilt site carries exactly the same claims, numbers and wording,
except that product and venue names are replaced with generic descriptions.

Beat kinds: text | list | flow | role | live | grid | specs.  Phases are (tab,
stop, caption). The bay spaces phases evenly and the system's story in
tools/stories.py draws each one; the stop only records where the phase sits in
the narrative. A grid body is (title, text) pairs, specs is (key, value) pairs;
either may carry a note, printed below it."""

def B(key, label, title, body, kind='text', tags=None, note=None):
    return dict(key=key, label=label, title=title, body=body, kind=kind, tags=tags, note=note)

SYSTEMS_A = [
  dict(
    id='JJ-SYS-01', slug='setup-agent', name='Compression Setup Agent', short='Setup Agent', facet='agents',
    kind='Production AI', read='3 min',
    title='Operations agent that collapsed a 3.5-hour bottleneck',
    lede='A production AI agent inside a live operations workflow, not a side chatbot. Bounded actions, operator visibility, and zero AI-initiated configuration errors in its first six months.',
    org='Quantile · LSEG', stage='0→1 launch', year='2025', role='Lead Product Manager',
    metrics=[('3.5h → 8m', 'setup time'), ('3×', 'run volume'), ('0', 'AI config errors / 6 mo')],
    ledger=('Production AI', '3.5h → 8m', 'setup time'),
    bay=dict(title='Setup agent · compression-run setup', sub='Bottleneck: senior engineering owns every setup',
             big='3.5h → 8m', big_sub='setup time',
             foot='Schematic, not the production interface · 3× volume at constant headcount · 0 AI config errors / 6 mo'),
    phases=[('Before', .14, 'Before: senior engineers own every setup, at 3.5 hours per run.'),
            ('Gate',   .44, 'Gate: HITL on. The agent may use only typed, reversible tools.'),
            ('After',  .82, 'After: ops runs an 8-minute cycle. Same headcount absorbs 3× volume.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'High-value compression-run setup depended on a lengthy senior-engineering workflow. It was reliable. It was also the throughput constraint: higher volume meant more expert hours the team did not have.'),
      B('decision', 'Decision', 'Product decision', 'Treat the bottleneck as an operations product, not a chatbot. The agent receives authorized live context (run state, configurations, client data) and acts only through typed, bounded surfaces. Operators stay in the loop.'),
      B('flow', 'Flow', 'Flow', [('Before', '3.5h expert setup', 'Senior engineering was the throughput bottleneck.'),
                                 ('Decision', 'Bounded agent in the workflow', 'Live context, typed actions, operator control.'),
                                 ('After', '8 minutes, 3× volume', 'Operations absorbed the load without added headcount.')], kind='flow'),
      B('pattern', 'System pattern', 'System pattern', ['Assembles only the context needed for the current run',
                                                        'Uses controlled tool actions rather than open-ended system access',
                                                        'Keeps operator visibility and intervention in the execution loop',
                                                        'Measures setup speed, throughput, and configuration quality in production'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Lead Product Manager. Owned 0→1 strategy and launch: framed the workflow, defined the agent boundary and success metrics, designed controls and rollout, and tied the product to operating leverage.',
        kind='role', tags='Bounded autonomy · Human visibility · Live context · Production quality metric'),
      B('impact', 'Impact', 'Impact', 'Setup fell from 3.5 hours to 8 minutes. Run volume scaled 3× at constant headcount. Zero AI-initiated configuration errors in the first six months.'),
    ],
    also=['incident-agent', 'cross-currency', 'valuation'],
  ),
  dict(
    id='JJ-SYS-02', slug='incident-agent', name='Incident Triage Agent', short='Incident Agent', facet='agents',
    kind='Production AI · MCP', read='3 min',
    title='Incident agent that returned 750+ engineering hours a year',
    lede='When something broke in production, ops still paged senior engineers by default. The agent gathers domain evidence first, sharpens the diagnosis, and escalates only when the evidence is incomplete.',
    org='Quantile · LSEG', stage='Production', year='2025', role='Lead Product Manager',
    metrics=[('4.5h → 11m', 'investigation'), ('−78%', 'escalations'), ('750+', 'eng hours / year')],
    ledger=('Production AI · MCP', '4.5h → 11m', 'investigation'),
    bay=dict(title='Incident agent · production support', sub='Incident opens · default path still pages engineering',
             big='4.5h → 11m', big_sub='expert triage → ops cycle',
             foot='Schematic, not the production interface · 750+ senior eng hours / year returned · escalate only when evidence is incomplete'),
    phases=[('Incident', .08, 'Incident: the default path still pages engineering. That is the bottleneck the agent removes.'),
            ('Evidence', .48, 'Evidence: two domain MCP servers gather run and ops facts before anyone is paged.'),
            ('Diagnose', .90, 'Diagnose: escalate only when the evidence is incomplete; otherwise resolve in ops.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Institutional production support depended on deep system knowledge accumulated over years. Investigations were slow and routinely escalated from operations to senior engineering.'),
      B('decision', 'Decision', 'Product decision', 'Build for diagnosis. The agent retrieves evidence through two domain-specific MCP servers, applies six years of production-support knowledge, and sharpens the diagnosis before anyone pages an expert.'),
      B('flow', 'Flow', 'Flow', [('Before', '4.5h investigation', 'Deep knowledge lived with a small set of experts.'),
                                 ('Decision', 'MCP-backed evidence triage', 'Retrieve domain evidence, then escalate only if needed.'),
                                 ('After', '11 minutes', 'Fewer escalations, engineering time returned.')], kind='flow'),
      B('owned', 'What I owned', 'What I owned', ['Framed the product as diagnosis, not chat: success meant fewer engineering pages, not more answers',
                                                  'Defined the two MCP domain boundaries and the escalation rule when evidence is incomplete',
                                                  'Tied launch criteria to investigation time and escalation rate in production'], kind='list'),
      B('pattern', 'System pattern', 'System pattern', ['Connects the agent to curated operational context through domain-specific MCP',
                                                        'Surfaces evidence relevant to the incident instead of generic answers',
                                                        'Structures triage so issues can be resolved or sharply scoped before escalation',
                                                        'Uses investigation time and escalation rate as production success criteria'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Lead Product Manager. Led development and launch, shaped domain boundaries and support workflows, and focused the product on actionable diagnosis, not generic Q&A.',
        kind='role', tags='Domain MCP · Evidence first · Escalation boundary · Expert time as KPI'),
      B('impact', 'Impact', 'Impact', 'Expert investigation fell from 4.5 hours to 11 minutes. Escalations to engineering dropped 78%. 750+ senior engineering hours a year went back to product development.'),
    ],
    also=['setup-agent', 'cross-currency', 'valuation'],
  ),
  dict(
    id='JJ-SYS-03', slug='cross-currency', name='Cross-Currency Compression', short='Cross-Currency', facet='markets',
    kind='0→1 · Market structure', read='3 min',
    title='Multilateral compression for trillions in trapped notional',
    lede='Banks held large cross-currency books that could only net in pairs. A central settlement path made network-wide offsets executable, so notional stuck in pairs became eligible to compress.',
    org='Quantile · LSEG', stage='0→1 launch', year='2024', role='Product Manager',
    metrics=[('+34%', 'notional reduction / run'), ('18 banks', '12 currency pairs'), ('$X.XT', 'eligible notional')],
    ledger=('0→1 · Market structure', '+34%', 'reduction per run'),
    bay=dict(title='Cross-currency compression · central settlement', sub='Before: banks can only net in pairs · network offsets sit unused',
             big='+34%', big_sub='reduction per run vs bilateral',
             foot='Schematic · eligible notional ≠ cash saved · 18 banks · 12 pairs'),
    phases=[('Gross',          .05, 'Plain view: pairwise links only. Network-wide offsets cannot clear yet.'),
            ('Run',            .40, 'Run: compatible offsets settle through one central service across the network.'),
            ('Compressed',     .78, 'Compressed: 18 banks, 34% more notional reduction per run than bilateral.'),
            ('Risk envelope',  .87, 'Risk envelope: notional falls while each book’s risk intent stays inside its constraints.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Cross-currency exposures were optimized in bilateral relationships. Offsets across the wider network sat unused because there was no settlement structure that could support a multilateral outcome.'),
      B('decision', 'Decision', 'Product decision', 'Launch multilateral cross-currency compression with a clearing house’s settlement service as counterparty. The engine finds compatible offsets across participants. Value only matters if eligibility, constraints, and settlement remain executable.'),
      B('flow', 'Flow', 'Flow', [('Before', 'Bilateral only', 'Offsets across the wider network were unreachable.'),
                                 ('Decision', 'Central settlement', 'A structure that could actually clear a multilateral result.'),
                                 ('After', 'Trillions unlocked', '18 banks, 34% more reduction per run.')], kind='flow'),
      B('plain', 'In plain terms', 'In plain terms', ['Banks hold large cross-currency positions. Pairwise netting left network-wide offsets stuck',
                                                      'Eligible notional means exposure that became eligible to enter the compression run. It is not revenue, AUM, or cash saved',
                                                      'A clearing house’s settlement service provided the counterparty, so a multilateral proposal could actually clear',
                                                      'Success was measured as notional made eligible and notional reduced per run, with risk intent held inside constraints'], kind='list'),
      B('owned', 'What I owned', 'What I owned', ['Owned the 0→1 launch: product design, eligibility rules, workflow, institutional onboarding, and GTM',
                                                  'Treated settlement design as part of the product: a mathematically good offset is worthless if it cannot clear',
                                                  'Kept the risk envelope explicit so compression did not silently change the book’s intent'], kind='list'),
      B('how', 'How it works', 'How it works', ['Expands optimization from bilateral pairings to a multilateral network',
                                                'Identifies economically compatible offsets across participants, not pairwise cancellation',
                                                'Uses the settlement structure so the reduced book remains executable',
                                                'Measures value in notional made eligible and notional eliminated, while the risk intent of the book stays inside constraints'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product Manager. Owned the 0→1 launch across product design, eligibility, workflow, institutional onboarding, and GTM.',
        kind='role', tags='Multilateral network · Settlement design · Eligibility · Executable outcome'),
      B('impact', 'Impact', 'Impact', '$X.XT of previously ineligible bilateral notional became available across 12 currency pairs. 18 banks achieved 34% greater notional reduction per run than bilateral optimization.'),
    ],
    also=['setup-agent', 'incident-agent', 'valuation'],
  ),
  dict(
    id='JJ-SYS-04', slug='valuation', name='Dual-Source Valuation', short='Valuation', facet='markets',
    kind='Reliability · Infrastructure', read='3 min',
    title='Dual-source valuation that caught discrepancies 48 hours earlier',
    lede='A late valuation mismatch can halt a multi-trillion compression cycle. An independent second source removed that single point of failure and moved failure upstream, while it was still cheap to fix.',
    org='Quantile · LSEG', stage='0→1 launch', year='2024', role='Product Manager',
    metrics=[('−91%', 'resubmissions'), ('48h', 'earlier detection'), ('$XT+', 'cycle notional')],
    ledger=('Reliability · Infrastructure', '−91%', 'resubmissions'),
    bay=dict(title='Dual-source valuation · before live', sub='Diff · rows outside the band fail early, not in the live window',
             big='48h', big_sub='earlier detection · −91% resubmissions',
             foot='Schematic · $XT+ is cycle notional under check, not revenue · 24 banks'),
    phases=[('Split', .14, 'Run an independent valuation beside internal marks, before live.'),
            ('Diff',  .50, 'Rows outside the tolerance band fail early, not mid-cycle.'),
            ('Lock',  .90, 'Lock only when sources agree. $XT+ is cycle notional under check.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Institution-scale compression cycles depended on consistent valuation across sources. A discrepancy found late could halt a live cycle and force an expensive resubmission.'),
      B('decision', 'Decision', 'Product decision', 'Create an independent valuation view and compare two sources before the live window. Move failure upstream, while it is still cheap.'),
      B('plain', 'In plain terms', 'In plain terms', ['Compression cycles only run if valuations agree. A late mismatch stops the room',
                                                      '$XT+ is the notional size of cycles under this check, not revenue or assets managed',
                                                      'An independent view compared to internal marks; differences outside a tolerance band fail early',
                                                      'Success was earlier detection and fewer expensive resubmissions. This is not a pricing product'], kind='list'),
      B('owned', 'What I owned', 'What I owned', ['Defined the product strategy: data quality as a control before live, not an ops cleanup',
                                                  'Launched the dual-source valuation and validation engine for institutional cycles',
                                                  'Tied success to detection lead time and resubmission rate across participating banks'], kind='list'),
      B('how', 'How it works', 'How it works', ['Produces an independent valuation view',
                                                'Compares results across two sources before live execution',
                                                'Surfaces discrepancies early enough for teams to resolve them',
                                                'Turns data quality from a late-stage failure into an explicit product control'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product Manager. Defined product strategy and launched the valuation and validation engine.',
        kind='role', tags='Independent valuation · Dual-source · Shift-left controls · Reliability KPI'),
      B('impact', 'Impact', 'Impact', 'Discrepancies surfaced 48 hours earlier. Failed-run resubmissions fell 91% across 24 banks running $XT+ cycles.'),
    ],
    also=['setup-agent', 'incident-agent', 'cross-currency'],
  ),
  dict(
    id='JJ-SYS-05', slug='fx-compression', name='FX & NDF Compression', short='FX & NDF', facet='markets',
    kind='FX · Production', read='3 min',
    title='FX compression with margin intelligence in the optimizer',
    lede='A mathematically good FX proposal still fails if margin or data disagree. Margin checks moved inside the optimizer, and four-source validation gated inputs before the live window.',
    org='Quantile · LSEG', stage='Production', year='2024', role='Product Manager',
    metrics=[('40+', 'live runs'), ('100%', 'proposal acceptance'), ('−94%', 'live failures')],
    ledger=('FX · Production', '40+', 'live runs'),
    bay=dict(title='FX compression · forwards & NDFs', sub='Book ready · good math still fails if margin or data disagree',
             big='100%', big_sub='proposal acceptance · 40+ live runs',
             foot='Schematic · gates decide the cut before live · NDF = non-deliverable forward'),
    phases=[('Book',   .05, 'FX forwards and NDFs in the book the optimizer will actually touch.'),
            ('Gates',  .42, 'Eligibility, clearing-house IM, and four-source checks cut bad proposals.'),
            ('Accept', .80, 'Accept only when gates agree, measured as live acceptance, not theory.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'FX optimization only creates value if the proposal survives margin constraints, data-quality checks, and live execution. Late validation made good math fail in production.'),
      B('decision', 'Decision', 'Product decision', 'Embed the clearing house’s margin API in the optimizer. Add a four-source validation layer around production inputs, before the live window.'),
      B('plain', 'In plain terms', 'In plain terms', ['FX forwards and NDFs (non-deliverable forwards) only compress if the proposal can clear margin and data checks',
                                                      'Putting the clearing house’s initial margin inside the optimizer stops “good math, bad live run”',
                                                      'Four independent sources must agree on critical inputs before the live window opens',
                                                      'Success was proposal acceptance and fewer live failures, measured across 40+ runs'], kind='list'),
      B('owned', 'What I owned', 'What I owned', ['Designed and shipped FX-forward and NDF compression with margin intelligence in the product',
                                                  'Embedded the clearing house’s margin API in the optimizer rather than validating after the fact',
                                                  'Added four-source validation as a pre-live gate and tied launch to acceptance and reliability'], kind='list'),
      B('how', 'How it works', 'How it works', ['Validates margin constraints inside the optimization workflow',
                                                'Cross-checks critical data across four sources',
                                                'Surfaces quality issues before the live production window',
                                                'Measures success through proposal acceptance and live-run reliability'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product Manager. Designed and shipped FX-forward and NDF compression with the clearing house’s margin API embedded in the optimizer.',
        kind='role', tags='Embedded margin API · Four-source validation · Pre-live quality gate · Acceptance KPI'),
      B('impact', 'Impact', 'Impact', '100% proposal acceptance across 40+ live runs. Four-source validation cut live-run failures 94%.'),
    ],
    also=['setup-agent', 'incident-agent', 'cross-currency'],
  ),
  dict(
    id='JJ-SYS-06', slug='platform', name='Agent Platform & Controls', short='Agent Platform', facet='agents',
    kind='Agent platform', read='3 min',
    title='A reusable control plane for five enterprise agent systems',
    lede='One-off agent integrations do not scale. A shared control plane for context, typed actions, approval, and evals made the next agent a reuse problem, not a prototype from zero.',
    org='Quantile · LSEG', stage='Production', year='2025', role='Lead Product Manager',
    metrics=[('5', 'enterprise systems'), ('MCP + APIs', 'reusable interfaces'), ('HITL + evals', 'production controls')],
    ledger=('Agent platform', '5', 'enterprise systems'),
    bay=dict(title='Agent Platform & Controls', sub='One plug path · five systems · scope expands when evals say so',
             big='5', big_sub='systems, one control model',
             foot='Schematic · same interfaces · one shared control spine'),
    phases=[('Context',  .18, 'Context: MCP servers and domain APIs expose only what the workflow needs.'),
            ('Actions',  .36, 'Actions: Pydantic-typed actions limit what an agent can attempt.'),
            ('Services', .48, 'Services: high-consequence logic stays deterministic, outside the model.'),
            ('HITL',     .68, 'HITL: a human approves the consequential step before it runs.'),
            ('Eval',     .97, 'Eval: shared QA baselines make production-ready a repeatable path.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Individual AI workflows were becoming one-off integrations. Production scale needed a repeatable way to expose domain context and actions while keeping behavior bounded, observable, and reviewable.'),
      B('decision', 'Decision', 'Product decision', 'Standardize human-supervised architecture: reusable MCP servers, domain APIs, Pydantic-typed actions, deterministic services, HITL gates, and shared evaluation / QA baselines.'),
      B('plain', 'In plain terms', 'In plain terms', ['Five agent systems on one pattern beat five bespoke prototypes',
                                                      'MCP and domain APIs expose context; typed actions limit what an agent can attempt',
                                                      'High-consequence steps stay in deterministic services with human approval gates',
                                                      'Shared evaluation and QA baselines make “production-ready” a repeatable path, not a one-off review'], kind='list'),
      B('owned', 'What I owned', 'What I owned', ['Standardized the product and control pattern across five enterprise agent systems',
                                                  'Defined the human-supervised architecture: interfaces, typed actions, HITL gates, and eval baselines',
                                                  'Treated agent development as a reusable product capability rather than a sequence of prototypes'], kind='list'),
      B('control', 'Control model', 'Control model', ['Typed actions constrain what an agent can attempt',
                                                      'Deterministic services keep high-consequence logic outside the model',
                                                      'Human approval gates consequential workflow steps',
                                                      'Evaluation and QA baselines create a repeatable path from prototype to production'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Lead Product Manager. Standardized the product and control pattern across five enterprise systems.',
        kind='role', tags='Reusable interfaces · Typed actions · Deterministic services · Evaluation baseline'),
      B('impact', 'Impact', 'Impact', 'New agent workflows reuse proven interfaces instead of starting from zero. Agent development became a product capability, not a sequence of prototypes.'),
    ],
    also=['setup-agent', 'incident-agent', 'cross-currency'],
  ),
]
