"""Systems JJ-SYS-07 to JJ-SYS-10.

07 is verbatim from johnjayasankar.com.

08-10 are John's independent products, the three featured on his Labs site
(labs.johnjayasankar.com). Their cases keep the live site's wording and extend it
with facts stated on each product's own public site, captured September 2026:
ride-lens2.vercel.app, rail-drop3.vercel.app and daylight-app-wine.vercel.app.
Nothing is inferred from code or invented. Figures shown in the stories are the
products' own sample data (RailDrop's sample board, Daylight's Balanced preset)
or clearly labelled illustrations.

The `lab` block carries the Labs site's card copy: number, category, tagline,
description, and what each product refuses to fake."""

from data_systems_a import B

SYSTEMS_B = [
  dict(
    id='JJ-SYS-07', slug='margin-simulator', name='OpenGamma What-If', short='Margin simulator', facet='markets',
    kind='0→1 · Pre-trade', read='3 min',
    title='Pre-trade simulator that made capital a decision, not a surprise',
    lede='A what-if engine that priced the next trade’s capital cost across venues - before the desk committed. Incremental vs standalone made portfolio offsets visible.',
    org='OpenGamma · Trading Technologies', stage='0→1', year='2022-23', role='Product Analyst',
    metrics=[('0→1', 'originated and shipped'), ('up to −30%', 'initial margin'), ('20+', 'enterprise clients')],
    ledger=('0→1 · Pre-trade', '0→1', 'originated and shipped'),
    bay=dict(title='OpenGamma · pre-trade what-if', sub='Portfolio margin known · the next trade’s capital impact is not',
             big='IM', big_sub='before execution · potential, not guaranteed',
             foot='Schematic pre-trade surface · simulate to decide venue, broker or product'),
    phases=[('Base',     .05, 'Current margin on the book. The next trade’s cost is still unknown.'),
            ('+ Trade',  .20, 'Hypothetical trade sits outside the book until you simulate venues.'),
            ('Simulate', .34, 'Same trade across CME SPAN, ICE IRM, and OTC - before you execute.'),
            ('Compare',  .70, 'Incremental vs standalone: offsets in the book can cut cost up to ~30% when they apply - observed potential, not a guarantee.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Front-office teams lacked a simple way to compare the incremental margin impact of a proposed trade across brokers, venues, and products before execution. Capital showed up after the fact.'),
      B('decision', 'Decision', 'Product decision', 'Build a what-if engine in the trading workflow: current portfolio plus a hypothetical trade, simulated against native clearing methodologies (CME SPAN and ICE IRM) across OTC and exchange-traded venues.'),
      B('flow', 'Flow', 'Flow', [('Current', 'Portfolio IM is known', 'Teams can see where they stand. They cannot see the next trade.'),
                                 ('What-if', 'Propose, then simulate', 'Add the hypothetical position and recompute margin before execution.'),
                                 ('Decide', 'Compare allocations', 'Cheaper venue, broker, or product becomes a pre-trade choice.')], kind='flow'),
      B('plain', 'In plain terms', 'In plain terms', ['Before you add a trade, you need its capital cost - not after the fill',
                                                      'The same trade can cost different amounts on CME SPAN, ICE IRM, or OTC',
                                                      'Incremental cost (on top of your book) can be lower than standalone when offsets exist',
                                                      '“Up to −30%” is observed potential when offsets apply - not a guaranteed savings for every trade'], kind='list'),
      B('owned', 'What I owned', 'What I owned', ['Originated and shipped the 0→1 what-if product from discovery through launch',
                                                  'Led discovery across trading, treasury, risk, and operations so the engine answered a real pre-trade question',
                                                  'Made incremental vs standalone cost a first-class product concept, not a spreadsheet side path'], kind='list'),
      B('how', 'How it works', 'How it works', ['Starts from the current portfolio, not a blank page',
                                                'Adds, edits, or removes a proposed position as a hypothetical',
                                                'Simulates initial margin across broker, venue, and product before execution',
                                                'Uses native clearing methodologies as validation anchors so the comparison is decision-grade'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product Analyst. Originated and shipped the 0→1 product. Led discovery across trading, treasury, risk, and operations.',
        kind='role', tags='Scenario before trade · Native methodology · Decision UX · Capital efficiency'),
      B('impact', 'Impact', 'Impact', 'Institutional clients identified allocations with up to 30% lower initial margin for equivalent risk. Discovery and adoption spanned 20+ enterprise clients: banks, asset managers, commodity firms, and hedge funds.'),
    ],
    also=['platform', 'ridelens', 'raildrop'],
  ),
  dict(
    id='JJ-SYS-08', slug='ridelens', name='RideLens', short='RideLens', facet='independent',
    kind='Labs · Consumer', read='5 min',
    title='RideLens: every ride, one comparison',
    lede='Live roads. Real rate cards. Uber, Lyft, Empower, and Curb ranked before you open four apps and guess.',
    org='Independent · Labs', stage='0→1 · live product', year='2026', role='Product and builder',
    metrics=[('4', 'providers, one board'), ('3', 'ways to rank a trip'), ('Honest', 'ranges stay ranges')],
    ledger=('Labs · Consumer', '4', 'providers, one board'),
    lab=dict(n='01', cat='Consumer', tagline='Every ride, one comparison.',
             blurb='Live roads. Real rate cards. Uber, Lyft, Empower, and Curb ranked before you open four apps and guess.',
             does=['Map the trip once on live roads, then line up four providers side by side',
                   'Rank the same quotes by Price, Soonest, or Value',
                   'Estimates move with traffic, time of day, hotspots, and weather'],
             rule='Ranges stay ranges.',
             rule_body='When a fare is a range, both ends stay on the board. RideLens never invents a midpoint to look decisive.'),
    live='https://ride-lens2.vercel.app/', embed=True,
    bay=dict(title='RideLens · compare board', sub='Illustrative trip · four providers, three sort rules',
             big='4 → 1', big_sub='providers → one board',
             foot='Illustrative quote types, not live fares · the final fare is always confirmed in the provider app'),
    phases=[('Route',   .12, 'Illustrative: map the trip once on live roads; conditions feed the marketplace model.'),
            ('Price',   .38, 'Illustrative: the same four quotes, ranked by lowest listed fare.'),
            ('Soonest', .62, 'Illustrative: the same quotes, ranked by soonest pickup.'),
            ('Value',   .86, 'Illustrative: fare and wait traded off. Ranges stay ranges.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Getting across town meant bouncing between apps, comparing stale screenshots in my head, and hoping the fare I saw was still the fare I would pay. Ranges got flattened into fake precision. Wait times lived in a different mental tab than price.'),
      B('decision', 'Decision', 'Product decision', 'Build one decision surface. Map the route once. Pull published rate cards and a marketplace that moves with time of day, weather, and hotspots. Keep estimates as estimates, ranges as ranges, and upfront quotes as upfront. Rank by Price, Soonest, or Value, then hand off to the provider to book.'),
      B('flow', 'Flow', 'Flow', [('Fragmented', 'Four apps, one guess', 'Price in one place. ETA in another. Memory in between.'),
                                 ('One surface', 'Route once, compare once', 'Same trip. Side-by-side cards. Rank modes you can trust.'),
                                 ('Decide', 'Pick, then book there', 'RideLens ranks. The provider still owns the ride.')], kind='flow'),
      B('does', 'What it does', 'What it does', ['Search From and To, or Quick fill a hub: JFK, LGA, EWR, Times Sq, Grand Central, or Brooklyn Bridge',
                                                 'Use your current location or swap the ends, then map the route once on live roads',
                                                 'Line up Uber, Lyft, Empower, and Curb side by side on one board',
                                                 'Rank the same quotes by Price, Soonest, or Value; ⌘Enter runs the compare',
                                                 'Open the provider to book. The final fare is always confirmed in the provider app'], kind='list'),
      B('contract', 'Contract', 'The comparison contract', [('Estimates stay estimates', 'A modeled fare is shown as an estimate, never dressed up as a quote.'),
                                                             ('Ranges stay ranges', 'When a fare is a range, both ends stay on the board. No invented midpoint.'),
                                                             ('Upfront stays upfront', 'An upfront price is kept distinct from anything modeled.'),
                                                             ('Expired quotes never win', 'A stale quote cannot take the top of the board.')],
        kind='grid', note='I wanted a product that respects uncertainty. The board keeps these rules whichever way it is sorted.'),
      B('model', 'Under the hood', 'Under the hood', ['Photon for place search and OSRM for routing on live roads',
                                                      'Fare math built on published rate cards',
                                                      'A marketplace model that tracks time, zone heat, and weather, so estimates update with traffic, time of day, and hotspots',
                                                      'Side-by-side provider cards that auto-refresh after the first compare'], kind='list'),
      B('why', 'Why I built it', 'Why I built it', ['I live in a city where the right ride changes with the clock, and where opening four apps is its own chore',
                                                    'I wanted a product that respects uncertainty: never invent a midpoint just to look decisive',
                                                    'The interesting work was the comparison contract, not another map widget'], kind='list'),
      B('built', 'How it was built', 'How it was built', ['I directed product design, ranking rules, and quote honesty end-to-end',
                                                          'Implemented and iterated the live app in Cursor - ownership of decisions and quality stays with me',
                                                          'Marketplace behavior is modeled from published rate cards and conditions; booking still happens on the provider',
                                                          'Shipped as a working product, not a pitch deck. Adoption claims are not the point of this case'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product and builder. Designed the comparison model, quote honesty rules, ranking modes, and the live marketplace surface.',
        kind='role', tags='Multi-provider · Live routing · Quote honesty · Price · Soonest · Value'),
      B('impact', 'Impact', 'Impact', 'A working product: Photon search, OSRM routing, side-by-side provider cards, and auto-refresh after the first compare. Built end-to-end in Cursor and shipped live. I made it because I kept paying the tax of not knowing which ride was actually better tonight.'),
      B('live', 'Live', 'Try the live product', 'Explore the working product below without leaving this case. The frame is the live app - not a mock - then open it full-size if you want the full journey.', kind='live'),
    ],
    also=['raildrop', 'daylight', 'iport'],
  ),
  dict(
    id='JJ-SYS-09', slug='raildrop', name='RailDrop', short='RailDrop', facet='independent',
    kind='Labs · Consumer', read='5 min',
    title='RailDrop: know when your train gets cheaper',
    lede='Book the trip. Watch every bookable Amtrak option across your window. One email when a listed fare actually drops. Never an invented price.',
    org='Independent · Labs', stage='0→1 · live product', year='2026', role='Product and builder',
    metrics=[('±1 day', 'default watch window'), ('1 email', 'only when it improves'), ('0', 'invented prices')],
    ledger=('Labs · Consumer', '±1 day', 'default watch window'),
    lab=dict(n='03', cat='Consumer', tagline='Know when your train gets cheaper.',
             blurb='Book the trip. Watch every bookable Amtrak option across your window. One email when a listed fare actually drops.',
             does=['Watch every bookable rail option across the day before, the day, and the day after',
                   'Scan immediately, then again morning, afternoon, and evening',
                   'One email when a listed fare beats what you paid'],
             rule='Never an invented price.',
             rule_body='If the live board is down, RailDrop says so. It never guesses a fare, a change fee, or an itinerary.'),
    live='https://rail-drop3.vercel.app/', embed=True,
    bay=dict(title='RailDrop · Amtrak fare watch', sub='Sample board · BOS → NYP · you paid $128',
             big='$128 → $47', big_sub='paid → cheapest listed',
             foot='Sample board from RailDrop’s own site · listed fares · confirm on Amtrak'),
    phases=[('Booked',   .10, 'Illustrative: stations, date, and what you actually paid become the baseline.'),
            ('Watching', .36, 'Illustrative: the first scan runs immediately, then morning, afternoon, and evening.'),
            ('Board',    .60, 'Illustrative: every bookable option across ±1 day, measured against what you paid.'),
            ('Alert',    .86, 'Illustrative: one email when a listed fare beats what you paid. Confirm on Amtrak.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Northeast Corridor trips are booked early for peace of mind, then the board keeps moving. Flexible tickets can be changed, but only if you notice the drop. Most people do not. They paid $128 and never learn Regional 95 is sitting at $47.'),
      B('decision', 'Decision', 'Product decision', 'Watch the corridor, not just the train you bought. Default window is travel day ±1. Compare against what you actually paid. Surface every eligible rail option. Alert once when the opportunity improves. Keep booking on Amtrak: copy the itinerary, confirm there, never invent a deep link or a fare.'),
      B('flow', 'Flow', 'Flow', [('Booked', 'You already paid', 'Peace of mind first. The board does not freeze for you.'),
                                 ('Watch', 'Same stations, every train', 'Regional, Acela, connections, not just your seat.'),
                                 ('Alert', 'One precise email', 'Opportunity improved. Confirm on Amtrak before you change anything.')], kind='flow'),
      B('how', 'How it works', 'How it works', [('Book on Amtrak', 'Whatever you actually paid is the number every train is measured against.'),
                                                ('Tell RailDrop the trip', 'Stations, date, and price. The window is searched immediately.'),
                                                ('One email when it drops', 'Confirm on Amtrak before you change anything.')],
        kind='grid', note='No account required. Watch a trip as a guest, and add an email only if you want fare-drop alerts.'),
      B('watch', 'The watch', 'The watch discipline', ['Same stations, every train: Regional, Acela, and connections, not just the train you already bought',
                                                      '±1 day by default: the day before, your travel day, and the day after. If tomorrow is cheaper than today, you should know',
                                                      'Checks immediately when a watch is created, then morning, afternoon, and evening; C rechecks on demand',
                                                      'Already booked a specific train? Add the train number and the board pins it next to the cheapest listed option',
                                                      'One precise alert: email only when the opportunity actually improves'], kind='list'),
      B('board', 'The board', 'Reading the board', [('Beats your train', 'Cheaper and not slower than yours, or faster and not more expensive.'),
                                                    ('Filters that fit a trip', 'Leave after, arrive by, a duration cap, and a 30-minute arrive buffer.'),
                                                    ('Change fees, only if you say so', 'Type an estimate or tap $10, $20, or $50. Change rules depend on Flexible, Value, or Saver, so no fee is ever invented.'),
                                                    ('What moved, and how close', 'The board shows what moved and how close departure is. The decision to change stays yours.'),
                                                    ('Built for the keyboard', 'J and K focus a train, H hides it, U undoes, Y copies you versus it, W copies the window, F copies Amtrak fields.'),
                                                    ('Shareable in one line', 'T copies stations, the cheapest listed train, and what you paid, for anyone else on the trip.')],
        kind='grid'),
      B('rules', 'Will not do', 'What it will not do', [('Invent Amtrak prices', 'If the live board is down, you see that, not a guess.'),
                                                        ('Fake an itinerary', 'No deep links into invented Amtrak itineraries. You copy trip details and book there.'),
                                                        ('Rebook for you', 'It watches and ranks. You book on Amtrak, then tell it what you actually paid.'),
                                                        ('Spam you', 'Alerts fire only when the opportunity actually improves.')], kind='grid'),
      B('why', 'Why I built it', 'Why I built it', ['I kept buying Flexible Amtrak tickets early, then learning too late that a later Regional was half the price',
                                                    'Existing tools either invent certainty or bury the signal in noise. I wanted quiet honesty',
                                                    'The product is the watch discipline: same stations, every rail option, alert only when it matters'], kind='list'),
      B('built', 'How it was built', 'How it was built', ['I directed the watch window, alert rule, and honesty constraints end-to-end',
                                                          'Implemented and iterated the live app in Cursor - product judgment and quality are mine',
                                                          'Alerts fire only when a listed fare beats what you paid; booking confirmation stays on Amtrak',
                                                          'A working launch, not a growth story. The case is about the discipline of the watch'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product and builder. Designed the watch window, honesty rules, alert discipline, and the live board that never pretends Amtrak is quieter than it is.',
        kind='role', tags='Fare watch · ±1 day board · No invented prices · You decide on Amtrak'),
      B('impact', 'Impact', 'Impact', 'A live product with immediate scans, scheduled rechecks, guest watches, optional email alerts, and a board that fails honestly when the source is down. Built end-to-end in Cursor. I made it after enough trips where the cheaper train was there the whole time. I just was not watching.'),
      B('live', 'Live', 'Try the live product', 'Explore the working product below without leaving this case. The frame is the live app - not a mock - then open it full-size if you want the full journey.', kind='live'),
    ],
    also=['ridelens', 'daylight', 'fx-compression'],
  ),
  dict(
    id='JJ-SYS-10', slug='daylight', name='Daylight', short='Daylight', facet='independent',
    kind='Labs · Native macOS', read='6 min',
    title='Daylight: your screen, through the day',
    lede='Adaptive display lighting for macOS. Warmth and brightness on a schedule you set - gradual, offline, and honest about what it is doing and why.',
    org='Independent · Labs', stage='Shipped · v1.0.0', year='2026', role='Product and builder',
    metrics=[('6', 'layers, one fixed order'), ('3', 'levels of certainty'), ('263', 'tests, no dependencies')],
    ledger=('Labs · Native macOS', '6', 'layers, one fixed order'),
    lab=dict(n='02', cat='Native', tagline='Your screen, through the day.',
             blurb='Warmth and brightness on a schedule you set - gradual, offline, and honest about what it is doing and why.',
             does=['Shift warmth and brightness gradually on a schedule, or follow the sun',
                   'Decide every control on one printed, six-layer ladder',
                   'Read back after every write, and say so when another app took over'],
             rule='Success is not evidence.',
             rule_body='Daylight separates what it asked for, what macOS accepted, and what it could read back and confirm.'),
    live='https://daylight-app-wine.vercel.app/', embed=False,
    bay=dict(title='Daylight · display schedule', sub='Balanced preset · warmth and brightness decided separately',
             big='6 layers', big_sub='one fixed order',
             foot='Schematic · step values from the Balanced preset · the sentence is one the app writes'),
    phases=[('Schedule', .12, 'Balanced preset: 6500 K by day, 4200 K at 19:00, 3200 K at 21:30, 2800 K at 23:30.'),
            ('Resolve',  .38, 'Six layers in a fixed order: the highest layer that speaks about a control wins it.'),
            ('Explain',  .62, 'An app rule holds warmth neutral while dimming still comes from the schedule, and a sentence says so.'),
            ('Confirm',  .86, 'Asked, accepted, confirmed: an API returning success is not evidence the display changed.')],
    beats=[
      B('broken', 'Broken', 'What was broken', 'Most display utilities either fight Night Shift and f.lux silently, claim medical outcomes they cannot prove, or hide what actually changed your screen. I wanted something honest: a schedule that survives time zones and DST, rules that do not discard half the state, and language that admits when macOS did not take the write.'),
      B('decision', 'Decision', 'Product decision', 'Ship a menu-bar app that runs the same schedule engine its website demonstrates. Put every source of control on one printed ladder of six layers, and decide warmth and brightness separately so a rule that only dims cannot discard the schedule’s warmth. Distinguish asked, accepted, and confirmed. Notice competing colour-table writers instead of fighting them. Never ask for location, network, or analytics.'),
      B('flow', 'Flow', 'Flow', [('Schedule', 'Through the day', 'Anchors on the clock. Fades in mired. Survives DST and midnight.'),
                                 ('Explain', 'Name the cause', 'Every state has a sentence. Precedence is printed, not implied.'),
                                 ('Confirm', 'Trust the readback', 'Success from an API is not evidence. Competition is reported.')], kind='flow'),
      B('does', 'What it does', 'What it does', ['Shifts warmth and brightness gradually on a schedule you set, from presets Balanced, Subtle, Extra Warm, and Follow the sun',
                                                 'Follow the sun uses real sunrise and sunset, computed on your Mac from a place you choose: 101 cities built in, or coordinates',
                                                 'Lives in the menu bar: warmth and brightness, every mode, a pause with a duration, and restore, all one click from the icon',
                                                 'A pause lasts fifteen minutes, an hour, until the next scheduled change, or until you say otherwise, and tells you when it ends',
                                                 'The icon fills in proportion to how warm the setting is, and shows paused and off as distinct shapes rather than colours',
                                                 'Schedules travel: Daylight imports the file its website writes, and a link carries a whole schedule to anyone else'], kind='list'),
      B('ladder', 'The ladder', 'Six layers, one fixed order', [('Restored', 'Restore normal output. Top of the ladder, overrules everything below.'),
                                                                ('Paused', 'Paused until you resume.'),
                                                                ('Manual override', 'You reached for the slider.'),
                                                                ('App rule', 'An app that needs true colour.'),
                                                                ('Workspace', 'Where you are working.'),
                                                                ('Schedule', 'A schedule, warm by evening. The base layer, if nothing above it speaks.')],
        kind='grid', note='The highest layer that speaks about a control wins it, and warmth and brightness are decided separately, so a rule that only dims cannot quietly discard your schedule’s warmth. There are no user-assignable priorities: a rules system you can predict beats one you can fully rewire.'),
      B('explain', 'Explainable', 'It tells you what it is doing', [('Every state has a sentence', 'Plain language naming whatever is responsible, written by the same resolver the app runs and checked against it across every combination of the six layers.'),
                                                                    ('Three levels of certainty', 'What it asked for, what macOS accepted, and what it could read back and confirm. Each display reports which applies. An API returning success is not evidence that anything changed.'),
                                                                    ('It notices the competition', 'f.lux and Night Shift write to the same colour table. Daylight reads back after every write and says so when something else has overwritten it. It will not fight another app, or disable one behind your back.')],
        kind='grid', note='“Your display is neutral because Colour Work is active for this app. Dimming comes from Balanced.” The app writes sentences like that one for every state.'),
      B('details', 'Details', 'The details that took the longest', [('Schedules that survive real life', 'Daylight-saving changes, time-zone moves, clocks corrected by hand, schedules that cross midnight, night shifts, non-Western weeks, polar day and night. Anchors follow the clock and fades follow elapsed time; a test pins the 23-hour day that once put a schedule an hour out.'),
                                                                     ('Fades paced by perception', 'Interpolation runs in mired rather than kelvin, because 2000 to 3000 K is a large visible change and 8000 to 9000 K is nearly invisible. A 90-minute ramp writes about once a minute instead of once a frame.'),
                                                                     ('Displays remembered properly', 'Settings key to a durable display identity, never an index that is reassigned on every dock and wake. Identical monitors that cannot be told apart are reported as ambiguous instead of guessed at.'),
                                                                     ('It refuses a suspicious baseline', 'Before adjusting anything it validates what normal means for a display. With f.lux running, the table once read back R 1.00 / G 0.36 / B 0.10; a test is pinned to those exact numbers.'),
                                                                     ('Getting out of the way', '⇧⌥⌘R restores normal output from anywhere with no permissions. Quitting restores your displays, and after a crash macOS restores the colour table itself, verified under SIGKILL, which is why there is no watchdog helper.'),
                                                                     ('Sunrise without a permission prompt', 'Solar times are computed on your Mac from a place you choose. It can suggest a starting point from your time zone, never asks macOS where you are, and makes no network requests.')],
        kind='grid'),
      B('claims', 'Not claimed', 'What it does not claim', ['A comfort and routine tool, not a medical one: it does not prevent eye damage, treat eye strain, or improve your sleep',
                                                            'No invented circadian, eye-health, or melatonin scores. There is no score of any kind',
                                                            'Temperature values are approximate display targets, not measurements of emitted light',
                                                            'Brightness is software dimming, not backlight control, and the app says so wherever the word appears',
                                                            'It does not calibrate your display or make its colour accurate, including in Colour Work mode'], kind='list'),
      B('privacy', 'Privacy', 'It stays on your Mac', [('Account', 'None'), ('Network requests', 'None, ever'), ('Location permission', 'Never asked'),
                                                       ('Analytics or telemetry', 'None'), ('Screen contents, keystrokes, camera', 'Never touched'),
                                                       ('Settings', 'One readable file to export, import, or delete'), ('History', 'Off by default; switching it off deletes what was kept')],
        kind='specs', note='If you turn on app rules, Daylight reads the identifier of the frontmost application while deciding what to do, and keeps no record of it.'),
      B('unfinished', 'Unfinished', 'Two things that are not finished', [('Multi-display on real hardware', 'Every path is written and covered against simulated devices, but only one display was attached during development. Daylight --diagnose shows what your own displays report.'),
                                                                         ('Backlight over DDC', 'External-monitor backlight control has unit-tested packet framing, but the hardware path has never exchanged a byte with a monitor, so it is off by default.')],
        kind='grid', note='Both are stated on the product’s own site, next to the download.'),
      B('why', 'Why I built it', 'Why I built it', ['I wanted display comfort without medical theatre, scores, or melatonin claims',
                                                    'Existing tools either hide failures or overwrite each other quietly. I wanted the opposite',
                                                    'The interesting work was the control model: one printed ladder, durable display identity, and honest certainty'], kind='list'),
      B('built', 'How it was built', 'How it was built', ['Directed product, design, and implementation in Cursor - ownership and quality judgment are mine',
                                                          'Native macOS with no third-party dependencies; it builds with Command Line Tools alone, no Xcode required',
                                                          '263 tests ship with the source, and the website runs the app’s own schedule engine and colour maths rather than a picture of it',
                                                          'Solar position follows the published NOAA algorithm and the colour-temperature approximation follows Kim et al. (2002), both implemented from their descriptions',
                                                          'Signed v1.0.0, 2.1 MB, for Apple Silicon and Intel on macOS 14 or later. Not notarised yet, so Gatekeeper needs one honest first-open step'], kind='list'),
      B('role', 'Role & tags', 'Role & tags', 'Product and builder. Designed the schedule model, the six-layer precedence ladder, certainty reporting, and the menu-bar product that stays out of the way.',
        kind='role', tags='Schedule fades · Explainable state · Readback certainty · No location permission'),
      B('impact', 'Impact', 'Impact', 'A signed macOS app (v1.0.0) with four schedule presets, app rules, pause and restore, durable display identity, and a website that runs the same schedule engine. Built end-to-end with no third-party dependencies. Not notarised yet - Gatekeeper needs one honest first-open step, and the site says so.'),
      B('live', 'Live', 'See the product', 'Daylight is a signed macOS menu-bar app. Its site runs the real schedule engine in the browser, explains Gatekeeper and certainty, and carries the download and the source.', kind='live'),
    ],
    also=['ridelens', 'raildrop', 'platform'],
  ),
]
